# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/baffin/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/baffin/proprietary/lib/libcapi2.so:system/lib/libcapi2.so \
    vendor/samsung/baffin/proprietary/lib/libdispmanx.so:system/lib/libdispmanx.so \
    vendor/samsung/baffin/proprietary/lib/libat_stubs.so:system/lib/libat_stubs.so \
    vendor/samsung/baffin/proprietary/lib/libWFC.so:system/lib/libWFC.so \
    vendor/samsung/baffin/proprietary/lib/libstagefrighthw_a.so:system/lib/libstagefrighthw_a.so \
    vendor/samsung/baffin/proprietary/lib/libsoc.so:system/lib/libsoc.so \
    vendor/samsung/baffin/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/baffin/proprietary/lib/libOMX.brcm.audio.aac.decoder.so:system/lib/libOMX.brcm.audio.aac.decoder.so \
    vendor/samsung/baffin/proprietary/lib/libusb_config.so:system/lib/libusb_config.so \
    vendor/samsung/baffin/proprietary/lib/libOMX.brcm.audio.mp3.encoder.so:system/lib/libOMX.brcm.audio.mp3.encoder.so \
    vendor/samsung/baffin/proprietary/lib/libtvservice.so:system/lib/libtvservice.so \
    vendor/samsung/baffin/proprietary/lib/libVCOS.so:system/lib/libVCOS.so \
    vendor/samsung/baffin/proprietary/lib/libbrcmmp3dec.so:system/lib/libbrcmmp3dec.so \
    vendor/samsung/baffin/proprietary/lib/libOMX.brcm.audio.amrnb.encoder.so:system/lib/libOMX.brcm.audio.amrnb.encoder.so \
    vendor/samsung/baffin/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/baffin/proprietary/lib/hw/gps.capri.so:system/lib/hw/gps.capri.so \
    vendor/samsung/baffin/proprietary/lib/hw/audio.usb.capri.so:system/lib/hw/audio.usb.capri.so \
    vendor/samsung/baffin/proprietary/lib/hw/audio.hdmi.capri.so:system/lib/hw/audio.hdmi.capri.so \
    vendor/samsung/baffin/proprietary/lib/hw/sensors.capri.so:system/lib/hw/sensors.capri.so \
    vendor/samsung/baffin/proprietary/lib/hw/alsa.default.so:system/lib/hw/alsa.default.so \
    vendor/samsung/baffin/proprietary/lib/hw/audio.primary.capri.so:system/lib/hw/audio.primary.capri.so \
    vendor/samsung/baffin/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/baffin/proprietary/lib/libbrcmheaacdecoder.so:system/lib/libbrcmheaacdecoder.so \
    vendor/samsung/baffin/proprietary/lib/libcontainers.so:system/lib/libcontainers.so \
    vendor/samsung/baffin/proprietary/lib/libbrcmamrnbarienc.so:system/lib/libbrcmamrnbarienc.so \
    vendor/samsung/baffin/proprietary/lib/libsoundspeed.so:system/lib/libsoundspeed.so \
    vendor/samsung/baffin/proprietary/lib/modules/dhd.ko:system/lib/modules/dhd.ko \
    vendor/samsung/baffin/proprietary/lib/modules/VoiceSolution.ko:system/lib/modules/VoiceSolution.ko \
    vendor/samsung/baffin/proprietary/lib/libat.so:system/lib/libat.so \
    vendor/samsung/baffin/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \
    vendor/samsung/baffin/proprietary/lib/libhdcp.so:system/lib/libhdcp.so \
    vendor/samsung/baffin/proprietary/lib/libOMX.brcm.audio.amrnb.decoder.so:system/lib/libOMX.brcm.audio.amrnb.decoder.so \
    vendor/samsung/baffin/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/baffin/proprietary/lib/libsmct.so:system/lib/libsmct.so \
    vendor/samsung/baffin/proprietary/lib/lib_SamsungRec_V01006.so:system/lib/lib_SamsungRec_V01006.so \
    vendor/samsung/baffin/proprietary/lib/libbrcm_ril.so:system/lib/libbrcm_ril.so \
    vendor/samsung/baffin/proprietary/lib/librpc.so:system/lib/librpc.so \
    vendor/samsung/baffin/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/baffin/proprietary/lib/libvcsm.so:system/lib/libvcsm.so \
    vendor/samsung/baffin/proprietary/lib/libBrcmOMX_Core.so:system/lib/libBrcmOMX_Core.so \
    vendor/samsung/baffin/proprietary/lib/libSoundAlive_VSP_ver312a.so:system/lib/libSoundAlive_VSP_ver312a.so \
    vendor/samsung/baffin/proprietary/lib/libOMX.brcm.audio.amrwb.decoder.so:system/lib/libOMX.brcm.audio.amrwb.decoder.so \
    vendor/samsung/baffin/proprietary/lib/libvchiq.so:system/lib/libvchiq.so \
    vendor/samsung/baffin/proprietary/lib/libomxmmal.so:system/lib/libomxmmal.so \
    vendor/samsung/baffin/proprietary/lib/libbrcmaacenc.so:system/lib/libbrcmaacenc.so \
    vendor/samsung/baffin/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/baffin/proprietary/lib/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \
    vendor/samsung/baffin/proprietary/lib/soundfx/libaudiopreprocessing.so:system/lib/soundfx/libaudiopreprocessing.so \
    vendor/samsung/baffin/proprietary/lib/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
    vendor/samsung/baffin/proprietary/lib/soundfx/libbundlewrapper.so:system/lib/soundfx/libbundlewrapper.so \
    vendor/samsung/baffin/proprietary/lib/soundfx/libdownmix.so:system/lib/soundfx/libdownmix.so \
    vendor/samsung/baffin/proprietary/lib/libvcos.so:system/lib/libvcos.so \
    vendor/samsung/baffin/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03007.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03007.so \
    vendor/samsung/baffin/proprietary/lib/libsoundalive.so:system/lib/libsoundalive.so \
    vendor/samsung/baffin/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/baffin/proprietary/lib/libtvservice_binder.so:system/lib/libtvservice_binder.so \
    vendor/samsung/baffin/proprietary/lib/libmmal.so:system/lib/libmmal.so \
    vendor/samsung/baffin/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/baffin/proprietary/lib/libOMX.brcm.audio.aac.encoder.so:system/lib/libOMX.brcm.audio.aac.encoder.so \
    vendor/samsung/baffin/proprietary/lib/libmmal_util.so:system/lib/libmmal_util.so \
    vendor/samsung/baffin/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/baffin/proprietary/lib/libImmVibeJ.so:system/lib/libImmVibeJ.so \
    vendor/samsung/baffin/proprietary/lib/libbrcmmp3enc.so:system/lib/libbrcmmp3enc.so \
    vendor/samsung/baffin/proprietary/lib/libOMX.brcm.audio.amrwb.encoder.so:system/lib/libOMX.brcm.audio.amrwb.encoder.so \
    vendor/samsung/baffin/proprietary/lib/libOMX.brcm.audio.mp3.decoder.so:system/lib/libOMX.brcm.audio.mp3.decoder.so \
    vendor/samsung/baffin/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/samsung/baffin/proprietary/lib/libmmal_vc.so:system/lib/libmmal_vc.so \
    vendor/samsung/baffin/proprietary/lib/libvchwtest_driver.so:system/lib/libvchwtest_driver.so \
    vendor/samsung/baffin/proprietary/lib/libvcfiled.so:system/lib/libvcfiled.so \
    vendor/samsung/baffin/proprietary/lib/libaacdecoderwrapper.so:system/lib/libaacdecoderwrapper.so \
    vendor/samsung/baffin/proprietary/lib/libBrcmOMX_Component.so:system/lib/libBrcmOMX_Component.so \
    vendor/samsung/baffin/proprietary/lib/libbrcmcutils.so:system/lib/libbrcmcutils.so \
    vendor/samsung/baffin/proprietary/lib/libatlog.so:system/lib/libatlog.so \
    vendor/samsung/baffin/proprietary/lib/libbrcmamrnbaridec.so:system/lib/libbrcmamrnbaridec.so \
    vendor/samsung/baffin/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/baffin/proprietary/lib/libbufpool.so:system/lib/libbufpool.so \
    vendor/samsung/baffin/proprietary/lib/libcate_rpc.so:system/lib/libcate_rpc.so \
    vendor/samsung/baffin/proprietary/lib/libbrcmparser.so:system/lib/libbrcmparser.so \
    vendor/samsung/baffin/proprietary/lib/libbrcmamrwbaridec.so:system/lib/libbrcmamrwbaridec.so \
    vendor/samsung/baffin/proprietary/lib/libhdmiaudio.so:system/lib/libhdmiaudio.so \
    vendor/samsung/baffin/proprietary/lib/libbrcmamrwbarienc.so:system/lib/libbrcmamrwbarienc.so \
    vendor/samsung/baffin/proprietary/lib/libmmal_components.so:system/lib/libmmal_components.so \
    vendor/samsung/baffin/proprietary/lib/libHDCPKeyManager.so:system/lib/libHDCPKeyManager.so \
    vendor/samsung/baffin/proprietary/lib/libuecodec.so:system/lib/libuecodec.so \
    vendor/samsung/baffin/proprietary/lib/libsthmb.so:system/lib/libsthmb.so \
    vendor/samsung/baffin/proprietary/lib/libbufmgmt.so:system/lib/libbufmgmt.so \
    vendor/samsung/baffin/proprietary/lib/libseckeyprov.so:system/lib/libseckeyprov.so \
    vendor/samsung/baffin/proprietary/usr/lib/alsa-lib/libbcm_hp_filter.so:system/usr/lib/alsa-lib/libbcm_hp_filter.so \
    vendor/samsung/baffin/proprietary/usr/lib/alsa-lib/libbcm_test_filter.so:system/usr/lib/alsa-lib/libbcm_test_filter.so \
    vendor/samsung/baffin/proprietary/usr/lib/alsa-lib/libasound_module_pcm_bcmfilter.so:system/usr/lib/alsa-lib/libasound_module_pcm_bcmfilter.so \
    vendor/samsung/baffin/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/samsung/baffin/proprietary/usr/idc/sec_touchscreen.idc:system/usr/idc/sec_touchscreen.idc \
    vendor/samsung/baffin/proprietary/vendor/lib/hw/hwcomposer.capri.so:system/vendor/lib/hw/hwcomposer.capri.so \
    vendor/samsung/baffin/proprietary/vendor/lib/hw/lights.capri.so:system/vendor/lib/hw/lights.capri.so \
    vendor/samsung/baffin/proprietary/vendor/lib/hw/camera.capri.so:system/vendor/lib/hw/camera.capri.so \
    vendor/samsung/baffin/proprietary/vendor/lib/hw/power.capri.so:system/vendor/lib/hw/power.capri.so \
    vendor/samsung/baffin/proprietary/vendor/lib/hw/gralloc.capri.so:system/vendor/lib/hw/gralloc.capri.so \
    vendor/samsung/baffin/proprietary/vendor/lib/egl/libGLES_vc4.so:system/vendor/lib/egl/libGLES_vc4.so \
    vendor/samsung/baffin/proprietary/bin/cate_rpc_util:system/bin/cate_rpc_util \
    vendor/samsung/baffin/proprietary/bin/vcos-version:system/bin/vcos-version \
    vendor/samsung/baffin/proprietary/bin/immvibed:system/bin/immvibed \
    vendor/samsung/baffin/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/baffin/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/baffin/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/baffin/proprietary/bin/emma:system/bin/emma \
    vendor/samsung/baffin/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/baffin/proprietary/bin/atrace:system/bin/atrace \
    vendor/samsung/baffin/proprietary/bin/glgps:system/bin/glgps \
    vendor/samsung/baffin/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/baffin/proprietary/bin/mttlogger:system/bin/mttlogger \
    vendor/samsung/baffin/proprietary/bin/gpslogd:system/bin/gpslogd \
    vendor/samsung/baffin/proprietary/bin/bkmgrd:system/bin/bkmgrd \
    vendor/samsung/baffin/proprietary/bin/vcdbg:system/bin/vcdbg \
    vendor/samsung/baffin/proprietary/bin/BCM4334B0_002.001.013.0679.0000_03_Samsung_BaffinSpurCancellAlwaysOn.hcd:system/bin/BCM4334B0_002.001.013.0679.0000_03_Samsung_BaffinSpurCancellAlwaysOn.hcd \
    vendor/samsung/baffin/proprietary/bin/vclmk:system/bin/vclmk \
    vendor/samsung/baffin/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/baffin/proprietary/bin/atxd:system/bin/atxd \
    vendor/samsung/baffin/proprietary/bin/tvserver:system/bin/tvserver \
    vendor/samsung/baffin/proprietary/bin/atx:system/bin/atx \
    vendor/samsung/baffin/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/baffin/proprietary/etc/Volume.db:system/etc/Volume.db \
    vendor/samsung/baffin/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/baffin/proprietary/etc/wifi/bcmdhd_sta.bin_b2:system/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/baffin/proprietary/etc/wifi/bcmdhd_apsta.bin_b2:system/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/baffin/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/baffin/proprietary/etc/DiamondVoice_NB.txt:system/etc/DiamondVoice_NB.txt \
    vendor/samsung/baffin/proprietary/etc/DiamondVoice_Filter_WB.txt:system/etc/DiamondVoice_Filter_WB.txt \
    vendor/samsung/baffin/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/baffin/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/baffin/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
    vendor/samsung/baffin/proprietary/etc/camera_info.ini:system/etc/camera_info.ini \
    vendor/samsung/baffin/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/samsung/baffin/proprietary/etc/DiamondVoice_Filter_NB.txt:system/etc/DiamondVoice_Filter_NB.txt \
    vendor/samsung/baffin/proprietary/etc/DiamondVoice_WB.txt:system/etc/DiamondVoice_WB.txt \
    vendor/samsung/baffin/proprietary/etc/apns-conf.xml:system/etc/apns-conf.xml \
    vendor/samsung/baffin/proprietary/etc/spn-conf.xml:system/etc/spn-conf.xml \
    vendor/samsung/baffin/proprietary/etc/asound.conf:system/etc/asound.conf \
    vendor/samsung/baffin/proprietary/etc/sensors.conf:system/etc/sensors.conf \
    vendor/samsung/baffin/proprietary/etc/gps/glconfig.xml:system/etc/gps/glconfig.xml \
    vendor/samsung/baffin/proprietary/etc/DiamondVoice_SF_Filter_NB.txt:system/etc/DiamondVoice_SF_Filter_NB.txt \
    vendor/samsung/baffin/proprietary/etc/DiamondVoice_SF_Filter_WB.txt:system/etc/DiamondVoice_SF_Filter_WB.txt
